import { NextResponse } from "next/server";
import { generateMessageWithAgent } from "@/src/lib/agent/client";
import { agentGenerateMessageInputSchema } from "@/src/lib/agent/schemas";
import { createActivity, createSalesMessage } from "@/src/lib/tools/lead-tools";

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const input = agentGenerateMessageInputSchema.parse(body);
    const output = await generateMessageWithAgent(input);
    const saved = await createSalesMessage(
      input.lead.id,
      input.generatedWebsite?.id ?? null,
      output,
    );
    await createActivity(input.lead.id, {
      type: "agent_generate_message",
      description: "Sales message generated by Agent API layer.",
      metadata: { messageId: saved.id, channel: output.channel, mode: output.mode },
    });
    return NextResponse.json({ ...output, messageId: saved.id });
  } catch (error) {
    const message = error instanceof Error ? error.message : "Unknown error";
    return NextResponse.json({ error: message }, { status: 400 });
  }
}
