import { NextResponse } from "next/server";
import { analyzeBusinessWithAgent } from "@/src/lib/agent/client";
import { agentAnalyzeBusinessInputSchema } from "@/src/lib/agent/schemas";
import { createActivity, updateLeadAnalysis } from "@/src/lib/tools/lead-tools";

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const input = agentAnalyzeBusinessInputSchema.parse(body);
    const output = await analyzeBusinessWithAgent(input);
    await updateLeadAnalysis(input.leadId, output);
    await createActivity(input.leadId, {
      type: "agent_analyze_business",
      description: "Business analysis generated by Agent API layer.",
      metadata: { mode: output.mode },
    });
    return NextResponse.json(output);
  } catch (error) {
    const message = error instanceof Error ? error.message : "Unknown error";
    return NextResponse.json({ error: message }, { status: 400 });
  }
}
