import { NextResponse } from "next/server";
import { generateWebsiteWithAgent } from "@/src/lib/agent/client";
import { agentGenerateWebsiteInputSchema } from "@/src/lib/agent/schemas";
import {
  createActivity,
  createGeneratedWebsite,
  ensureLeadForWebsiteGeneration,
} from "@/src/lib/tools/lead-tools";

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const input = agentGenerateWebsiteInputSchema.parse(body);
    const resolvedLeadId = await ensureLeadForWebsiteGeneration(input);
    const output = await generateWebsiteWithAgent(input);
    const saved = await createGeneratedWebsite(resolvedLeadId, output);
    await createActivity(resolvedLeadId, {
      type: "agent_generate_website",
      description: "Personalized website generated by Agent API layer.",
      metadata: { generatedWebsiteId: saved.id, demoSlug: saved.demo_slug, mode: output.mode },
    });
    return NextResponse.json({
      ...output,
      generatedWebsiteId: saved.id,
      demoSlug: saved.demo_slug,
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : "Unknown error";
    return NextResponse.json({ error: message }, { status: 400 });
  }
}
